global:
  istioNamespace: istio-system
  hub: docker.io/istio
  tag: 1.20.0

base:
  enabled: true

istiod:
  enabled: true
  pilot:
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 1000m
        memory: 4096Mi
  meshConfig:
    enableAutoMtls: true
  pilot:
    env:
      PILOT_ENABLE_STATUS: true
    autoscaleEnabled: true
    replicaCount: 1
  sidecarInjectorWebhook:
    enableNamespacesByDefault: false
  validationWebhook:
    enabled: true

gateway:
  name: istio-ingressgateway
  enabled: true
  injectionTemplate: gateway
  service:
    type: LoadBalancer
    ports:
    - name: http2
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

monitoring:
  enabled: true
  namespace: monitoring
  services:
    grafana:
      host: grafana.local
      port: 80
    prometheus:
      host: prometheus.local
      port: 9090
    alertmanager:
      host: alertmanager.local
      port: 9093 