apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-setup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joferson/-monitoring-stack.git
    targetRevision: HEAD
    path: istio/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - RespectIgnoreDifferences=true 