apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.0.0
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          enabled: false
        alertmanager:
          enabled: false
        prometheus:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        prometheusOperator:
          enabled: true
          admissionWebhooks:
            enabled: true
            failurePolicy: Ignore
            certManager:
              enabled: false
          tls:
            enabled: false
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          annotations:
            argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 